// List Movie
export const LIST_MOVIE_REQUEST = 'LIST_MOVIE_REQUEST'
export const SEARCH_MOVIE_REQUEST = 'SEARCH_MOVIE_REQUEST'
export const LIST_MOVIE_SUCCESS = 'LIST_MOVIE_SUCCESS'
export const LIST_MOVIE_FAILURE = 'LIST_MOVIE_FAILURE'

// List Movie
export const DETAIL_MOVIE_REQUEST = 'DETAIL_MOVIE_REQUEST'
export const DETAIL_MOVIE_SUCCESS = 'DETAIL_MOVIE_SUCCESS'
export const DETAIL_MOVIE_FAILURE = 'DETAIL_MOVIE_FAILURE'

// List Movie Favorit
export const FAVORIT_MOVIE_SET = 'FAVORIT_MOVIE_SET'
export const FAVORIT_MOVIE_REMOVE = 'FAVORIT_MOVIE_REMOVE'

